### ISSUE TITLE
Stable docs not building

### ISSUE THREAD

**Issue by jishnub** [JuliaLinearAlgebra/BandedMatrices.jl#282]
I noticed that the [permissions of GITHUB_TOKEN](https://github.com/JuliaLinearAlgebra/BandedMatrices.jl/actions/runs/3578304165/jobs/6018304263) are different in this repo compared to others.
In this repo:
```console
GITHUB_TOKEN Permissions
  Contents: write
  Metadata: read
```
In, say, [StaticArrays](https://github.com/JuliaArrays/StaticArrays.jl/actions/runs/3569185857/jobs/5998877411), where the docs do build,
```console
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
```
Perhaps we need to enable permissions for this, to get the docs to build?

At the same time I'm not entirely sure about the interplay between `GITHUB_TOKEN` and `DOCUMENTER_KEY`, and if the ssh token is enough for docs to build, and if it's set correctly for this repo. In any case, perhaps enabling permissions for `GITHUB_TOKEN` can't hurt.

**Comment by dlfivefifty** [comment]
I don't understand actions / tokens at all so just tell me exactly what you want me to change

**Comment by jishnub** [comment]
Could you check Settings > Actions> General > Workflow permissions and see if the permissions are enabled?

**Comment by dlfivefifty** [comment]
It says they are enabled

**Comment by jishnub** [comment]
Could you check if the Documenter key in https://github.com/JuliaLinearAlgebra/BandedMatrices.jl/settings/keys has read/write permissions?

**Comment by dlfivefifty** [comment]
Hmm there are no keys.... how do I add it?

**Comment by jishnub** [comment]
Oh, I see, that probably explains what's going on. You can add a key by following the instruction at https://documenter.juliadocs.org/stable/man/hosting/#travis-ssh, and adding the public key and secret that's generated. The key doesn't need to be named while creating it, but the secret must be called `DOCUMENTER_KEY`, as that's the name used in the TagBot currently

**Comment by dlfivefifty** [comment]
OK I added it DOCUMENTER_KEY to "Repository secrets" and a "Documenter" Deploy key hopefully that resolves it

**Comment by jishnub** [comment]
This is fixed now
