### ISSUE TITLE
`Adjoint`/`Transpose` don't define `bandeddata`

### ISSUE THREAD

**Issue by jishnub** [JuliaLinearAlgebra/BandedMatrices.jl#288]
```julia
julia> B = BandedMatrix(0 => rand(10), 1=>rand(9), -2=>rand(8));

julia> C = B';

julia> BandedMatrices.isbanded(C)
true

julia> BandedMatrices.bandeddata(C)
ERROR: Override bandeddata(::LinearAlgebra.Adjoint{Float64, BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}}})
```

**Comment by dlfivefifty** [comment]
Why would they? `bandeddata` is only for the case `MemoryLayout(C) isa BandedColumns`.

In this case `MemoryLayout(C) isa BandedRows` and you can do `bandeddata(C')` to get the underlying data.

**Comment by jishnub** [comment]
That's not always the case, e.g. for a `Diagonal`. In any case, perhaps I'm looking for something else: is there a way to extract the equivalent of `bandeddata` from a banded `AbstractMatrix`?

**Comment by jishnub** [comment]
There is also an issue of consistency here:
```julia
julia> D = Diagonal([1,2]);

julia> A = Adjoint(D);

julia> MemoryLayout(A) == MemoryLayout(D)
true

julia> BandedMatrices.bandeddata(D)
1×2 Matrix{Int64}:
 1  2

julia> BandedMatrices.bandeddata(A)
ERROR: Override bandeddata(::Adjoint{Int64, Diagonal{Int64, Vector{Int64}}})
```

**Comment by dlfivefifty** [comment]
> In any case, perhaps I'm looking for something else: is there a way to extract the equivalent of bandeddata from a banded AbstractMatrix?

No. If there was it would in general be very slow. i.e. why not just use getindex `C[k,j]` in this case directly?

> There is also an issue of consistency here:

Probably just need to overload `bandeddata` for all `DiagonalLayout` to just call `diagonaldata`
