### ISSUE TITLE
When to use BandedMatrices over static arrays?

### ISSUE THREAD

**Issue by Veenty** [JuliaLinearAlgebra/BandedMatrices.jl#391]
Is there any good rule of thumb for when to use this package vs a simple static matrix?

**Comment by dlfivefifty** [comment]
I don't understand what you mean by "Static matrix", you mean StaticArrays.jl? If your matrix is small enough that `SMatrix` is practical then you should probably use that....

**Comment by jishnub** [comment]
Closing as there's nothing to do here. For a detailed comparison, please consider asking on the Julia discourse
